# Generated by Django 4.2 on 2025-09-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_querylog_dataset_alter_querylog_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='datasets/')),
                ('dataset_type', models.CharField(choices=[('ocean', 'Oceanographic'), ('fisheries', 'Fisheries'), ('biodiversity', 'Molecular Biodiversity')], default='ocean', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
