# Generated by Django 4.2 on 2025-09-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_delete_uploadeddataset_remove_querylog_dataset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='querylog',
            name='domain',
            field=models.CharField(blank=True, help_text='Which dataset was used: oceanographic / fisheries / biodiversity', max_length=50, null=True),
        ),
    ]
